In [1]:
from sound_generator import SoundGenerator
from IPython.display import Audio

In [2]:
sg = SoundGenerator()
# sg.info()

2021-08-17 13:30:56.585 | INFO     | sound_generator:__init__:73 - Using default config
2021-08-17 13:30:56.589 | INFO     | sound_generator:load_config:122 - Config loaded
2021-08-17 13:30:59.775 | INFO     | sound_generator:load_model:130 - Model loaded


In [9]:
success, audio = sg.get_prediction({
    "input_pitch": 60,
    "pitch": 60,
    "velocity": 100,
    "heuristic_measures": [0.] * sg.conf.num_measures,
    "latent_sample": [0.5] * sg.conf.latent_dim
})

2021-08-17 13:03:32.935 | INFO     | sound_generator:_prepare_inputs:155 - Preparing inputs
2021-08-17 13:03:32.937 | INFO     | sound_generator:get_prediction:209 - Getting prediction
2021-08-17 13:03:33.092 | INFO     | sound_generator:get_prediction:211 - Transforming prediction
2021-08-17 13:03:33.095 | INFO     | sound_generator:get_prediction:213 - De-normalizing prediction
2021-08-17 13:03:33.114 | INFO     | sound_generator:get_prediction:217 - Synthesising audio


In [10]:
print(success)
len(audio)

True


64000

In [11]:
Audio(audio, rate=16000)

In [3]:

sg.conf.data_handler.remap_measures

True

In [5]:
measure_names = sg.conf.data_handler.measures_names
measures = dict((k, 0.5) for k in measure_names)
measures = sg.conf.data_handler.measures_mapping(measures)

In [6]:
measures

{'inharmonic': <tf.Tensor: shape=(), dtype=float32, numpy=0.65328276>,
 'even_odd': <tf.Tensor: shape=(), dtype=float32, numpy=0.75249815>,
 'sparse_rich': <tf.Tensor: shape=(), dtype=float32, numpy=0.9832639>,
 'attack_rms': <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 'decay_rms': <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 'attack_time': <tf.Tensor: shape=(), dtype=float32, numpy=0.96989703>,
 'decay_time': <tf.Tensor: shape=(), dtype=float32, numpy=0.294437>,
 'bass': <tf.Tensor: shape=(), dtype=float32, numpy=0.85013974>,
 'mid': <tf.Tensor: shape=(), dtype=float32, numpy=0.6677948>,
 'high_mid': <tf.Tensor: shape=(), dtype=float32, numpy=0.9549273>,
 'high': <tf.Tensor: shape=(), dtype=float32, numpy=0.988638>}