In [1]:
import os
import tensorflow as tf
from prepare import CompleteTFRecordProvider
from IPython.display import Audio
import numpy as np


base_dir = "d:\soundofai\\cleaned_nsynth\\new"

dp = CompleteTFRecordProvider(os.path.join(base_dir, "train.tfrecord"))

In [2]:
dataset = dp.get_batch(1, shuffle=False, repeats=1)

In [4]:
data_iter = iter(dataset)

In [5]:
e = next(data_iter)
note = np.squeeze(e["note_number"])
instr_id = np.squeeze(e["instrument_id"])
vel = np.squeeze(e["velocity"])

print(instr_id, note, vel)

Audio(np.squeeze(e["audio"]), rate=16000)

1 82 50


In [40]:
h_freq = e["h_freq"]

In [31]:
n = h_freq.numpy()

In [34]:
type(n)

bytes

In [51]:
tf.io.decode_raw(h_freq.numpy()[0], out_type=tf.int8)

<tf.Tensor: shape=(40065,), dtype=int8, numpy=array([ 8,  7, 18, ...,  0,  0,  0], dtype=int8)>

In [56]:
s = tf.io.parse_tensor(h_freq[0], out_type=tf.string)

In [57]:
f = tf.io.parse_tensor(s, out_type=tf.float32)

In [58]:
f

<tf.Tensor: shape=(1001, 10), dtype=float32, numpy=
array([[ 913.84784, 1905.8328 , 2828.8345 , ..., 7439.2188 , 7810.133  ,
           0.     ],
       [ 918.0597 , 1907.2646 , 2828.1704 , ..., 7449.329  , 7824.845  ,
           0.     ],
       [ 901.3496 , 1901.2125 , 2831.1777 , ..., 7412.7324 , 7810.133  ,
           0.     ],
       ...,
       [ 931.3708 , 1875.6438 , 2829.2224 , ..., 7540.623  , 7810.133  ,
           0.     ],
       [ 931.3708 , 1875.6438 , 2829.2224 , ..., 7540.623  , 7810.133  ,
           0.     ],
       [ 931.3708 , 1875.6438 , 2829.2224 , ..., 7540.623  , 7810.133  ,
           0.     ]], dtype=float32)>

In [59]:
h_freq = e["h_freq"]
serialized = tf.io.parse_tensor(h_freq[0], out_type=tf.string)
h_freq_tensor = tf.io.parse_tensor(serialized, out_type=tf.float32)

In [60]:
h_freq_tensor

<tf.Tensor: shape=(1001, 10), dtype=float32, numpy=
array([[ 913.84784, 1905.8328 , 2828.8345 , ..., 7439.2188 , 7810.133  ,
           0.     ],
       [ 918.0597 , 1907.2646 , 2828.1704 , ..., 7449.329  , 7824.845  ,
           0.     ],
       [ 901.3496 , 1901.2125 , 2831.1777 , ..., 7412.7324 , 7810.133  ,
           0.     ],
       ...,
       [ 931.3708 , 1875.6438 , 2829.2224 , ..., 7540.623  , 7810.133  ,
           0.     ],
       [ 931.3708 , 1875.6438 , 2829.2224 , ..., 7540.623  , 7810.133  ,
           0.     ],
       [ 931.3708 , 1875.6438 , 2829.2224 , ..., 7540.623  , 7810.133  ,
           0.     ]], dtype=float32)>