In [1]:
%matplotlib inline

import numpy as np

from create_model_fb import create_model
# from data_generator import DataGenerator
from data_generator_fb import DataGenerator
from config import get_config

In [2]:
conf = get_config()
batch_size = 4
# f = "bright_vs_dark"
# conf["features"] = [f]
conf["valid_split"] = 0.0

data_gen = DataGenerator(conf, batch_size)

2021-06-06 14:39:06.586 | INFO     | data_generator_fb:__init__:32 - DataGenerator instantiated
2021-06-06 14:39:06.588 | INFO     | data_generator_fb:preprocess:37 - Preprocessing examples
100%|██████████| 10999/10999 [00:01<00:00, 10127.98it/s]
2021-06-06 14:39:07.676 | INFO     | data_generator_fb:preprocess:65 - Examples in training set: 10999
2021-06-06 14:39:07.677 | INFO     | data_generator_fb:preprocess:66 - Examples in validation set: 0
2021-06-06 14:39:07.677 | INFO     | data_generator_fb:__init__:34 - Preprocessing complete


In [3]:
model = create_model(conf, data_gen.input_shapes)
model.load_weights("checkpoints/fb_qualities_loss_0.3983_acc_0.34.h5")

In [4]:
data = iter(data_gen.generator("train"))

In [5]:
x, y = next(data)
preds = model.predict(x)

for index in range(0, batch_size):
    print("="*10)
    print((preds[index] > 0.5).astype("uint8"))
    print(y["output"][index])

[0 0 0 0 0 0 0 0 0 0 0 0]
[0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0 1 0]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0]
[0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0]
[1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1.]
